---

- hosts: localhost
  gather_facts: true
  roles:
    - core

- hosts: chroot
  gather_facts: true
  roles:
    - core
    - xorg
    # Desktop Environment & Windows Managers
    - i3
    #- gnome