- name: install
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - gnome
    - gnome-tweaks
    - nautilus-sendto
    - gnome-nettool
    - gnome-usage
    - gnome-multi-writer
    - adwaita-icon-theme
    - xdg-user-dirs-gtk
    - fwupd
    - arc-gtk-theme
    - gdm
    - nautilus
    - gnome-terminal
    - firefox

- name: enable display manager service on start
  systemd:
    name: gdm
    enabled: yes
  when:
    - ansible_facts['is_chroot'] is false

- name: enable display manager service on start inside chroot
  file:
    path: /etc/systemd/system/display-manager.service
    src: /usr/lib/systemd/system/gdm.service
    owner: root
    group: root
    state: link
  when:
    - ansible_facts['is_chroot'] is true

- name: Disable wayland on gdm
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '^#WaylandEnable'
    line: WaylandEnable=false

- name: Disable some icons from the application list
  ansible.builtin.lineinfile:
    path: "/usr/share/applications/{{ item }}"
    regexp: '^NoDisplay='
    line: NoDisplay=true
  loop:
    - avahi-discover.desktop
    - bssh.desktop
    - bvnc.desktop
    - lstopo.desktop
    - gnome-nettool.desktop
    - qv4l2.desktop
    - qvidcap.desktop