- name: install
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - gnome
    - gnome-tweaks
    - nautilus-sendto
    - gnome-nettool
    - gnome-usage
    - gnome-multi-writer
    - adwaita-icon-theme
    - xdg-user-dirs-gtk
    - fwupd
    - arc-gtk-theme
    - gdm
    - nautilus
    - gnome-terminal
    - firefox

- name: enable display manager service on start
  systemd:
    name: gdm
    enabled: yes
  when:
    - ansible_facts['is_chroot'] is false